const Task = require('./../models/taskModel')
// const catchAsync = require('./../utils/catchAsync')
// const AppError = require('./../utils/appError')
const factory = require('./handlerFactory')

exports.create = factory.createOne(Task)
exports.getAll = factory.getAll(Task)
exports.getTask = factory.getOne(Task)
exports.update = factory.updateOne(Task)
exports.delete = factory.deleteOne(Task)
